---
apiVersion: v1
kind: Namespace
metadata:
  name: petclinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic
  namespace: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: acrpc.azurecr.io/petclinic:changeme_tag
        name: petclinic
        readinessProbe:
          httpGet:
        #    path: /health.php
            port: 8080
        livenessProbe:
          httpGet:
        #    path: /health.php
            port: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "64Mi"
          limits:
            cpu: "1000m"
            memory: "4096Mi"
      imagePullSecrets:
        - name: acr-petclinic
---
apiVersion: v1
kind: Service
metadata:
  #annotations:
    #service.beta.kubernetes.io/azure-load-balancer-resource-group: devops_team
    #service.beta.kubernetes.io/azure-dns-label-name: petclinic
  name: petclinic
  namespace: petclinic
spec:
  selector:
    app: petclinic
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  #loadBalancerIP: 40.76.48.4
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic
  namespace: petclinic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  
